services:
  app:
    image: jefoso/voting-kata:rust-api-dev
    build:
      context: .
    ports:
      - "3000:3000"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 250m