services:
  report-api:
    build:
      context: .
    container_name: report-api
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://report-api-database-postgres:5432/sales_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      report-api-database-postgres:
        condition: service_healthy
    networks:
      - data-kata-net
