server:
  port: 9008

scheduler:
  batch-size: 5

kafka:
  bootstrap-servers: ${KAFKA_HOST:localhost:9092}

salesman:
  url: ${SALESMAN_API_URL:http://localhost:8089}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5439/data-collector-db}
    username: ${SPRING_DATASOURCE_USERNAME:user}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect