services:
  source-db-webserver-postgres:
    image: postgres:18-alpine
    container_name: data-kata-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: sales_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d sales_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - data-kata-net

  web-server:
    depends_on:
      source-db-webserver-postgres:
        condition: service_healthy
    restart: on-failure  
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: sales_db
    networks:
      - data-kata-net


volumes:
  source_db_webserver_postgres_data:
