services:

  # Prometheus
  prometheus:
    image: prom/prometheus:v2.51.1
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      - data-kata-net

  # Grafana
  grafana:
    image: grafana/grafana:10.4.2
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_LOG_LEVEL=info
      - GF_AUTH_BASIC_ENABLED=false
    networks:
      - data-kata-net
