services:
  file-viewer:
    image: alpine
    volumes:
      - ../data:/data
    command: tail -f /dev/null
    networks:
      - data-kata-net

  web-server:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: sales_db
    networks:
      - data-kata-net
