version: '3.8'

services:
  file-viewer:
    image: alpine
    volumes:
      - ./data:/data
    command: tail -f /dev/null

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: datakata
    command: ['postgres', '-c', 'wal_level=logical']
    networks:
      - broker-kafka    
    volumes:
      - ./scripts/database/init.sql:/docker-entrypoint-initdb.d/init.sql      
    ports:
      - "5432:5432"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.1
    container_name: flink-agg-zookeeper
    networks:
      - broker-kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.1
    container_name: flink-agg-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    networks:
      - broker-kafka      
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1   

  kafdrop:
    image: obsidiandynamics/kafdrop:4.0.1
    container_name: flink-agg-kafdrop
    networks: 
      - broker-kafka
    depends_on:
      - kafka
    ports:
      - 19000:9000
    environment:
      KAFKA_BROKERCONNECT: kafka:29092  

  debezium:
    image: debezium/connect:2.5.0.Final
    restart: always
    container_name: poc_debezium
    hostname: debezium
    networks:
      - broker-kafka    
    depends_on:
      - postgres
      - kafka
    ports:
      - '8083:8083'
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      STATUS_STORAGE_TOPIC: connect_statuses
      OFFSET_STORAGE_TOPIC: connect_offsets
      KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      VALUE_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      ENABLE_DEBEZIUM_SCRIPTING: 'true'         



  web-server:
    build: ./web-server
    ports:
      - "8080:8080"

networks: 
  broker-kafka:
    driver: bridge       
