services:
  kafka-connect-lineage-emitter:
    build:
      context: ./kafka-connect-lineage-emitter
      dockerfile: Dockerfile
    environment:
      MARQUEZ_API_URL: http://marquez-api:4000
      KAFKA_CONNECT_URL: http://kafka-connect:8083
    depends_on:
      - kafka-connect
    networks:
      - data-kata-net
  marquez-db:
    image: postgres:18-alpine
    container_name: marquez-db
    environment:
      POSTGRES_USER: marquez
      POSTGRES_PASSWORD: marquez
      POSTGRES_DB: marquez
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U marquez -d marquez"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5434:5432"
    volumes:
      - marquez-db-data:/var/lib/postgresql/data
    networks:
      - data-kata-net

  marquez-api:
    image: marquezproject/marquez:0.51.1
    container_name: marquez-api
    depends_on:
      marquez-db:
        condition: service_healthy
    command: ["./entrypoint.sh", "api"]
    environment:
      MARQUEZ_PORT: 4000
      MARQUEZ_ADMIN_PORT: 5001
      POSTGRES_HOST: marquez-db
      POSTGRES_PORT: 5432
      POSTGRES_DB: marquez
      POSTGRES_USER: marquez
      POSTGRES_PASSWORD: marquez
      SEARCH_ENABLED: False
    ports:
      - "4000:4000"
      - "5001:5001"
    networks:
      - data-kata-net

  marquez-web:
    image: marquezproject/marquez-web:0.51.1
    container_name: marquez-web
    depends_on:
      - marquez-api
    environment:
      MARQUEZ_HOST: marquez-api
      MARQUEZ_PORT: 4000
      WEB_PORT: 3000
    ports:
      - "3000:3000"
    networks:
      - data-kata-net

volumes:
  marquez-db-data:
    driver: local